"""
Metrics Collector — Zero-Token Repository Analysis Engine

Collects real metrics from all repositories using only:
  - git CLI (commit history, contributors, branches)
  - filesystem traversal (file counts, LoC by language)
  - config file parsing (dependencies from pyproject.toml / Cargo.toml / package.json / go.mod)
  - regex heuristics (security patterns)

Zero LLM tokens consumed.
"""

import json
import logging
import math
import os
import re
import subprocess
import tomllib
from collections import Counter, defaultdict
from collections.abc import Iterator
from dataclasses import asdict, dataclass, field
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

from cerebro.core.metrics_profiles import (
    Archetype,
    Dimension,
    HealthResult,
    StackLayer,
    classify_archetype,
    classify_layer,
    score_repo,
)

logger = logging.getLogger("cerebro.metrics")

# ---------------------------------------------------------------------------
# Language / extension maps
# ---------------------------------------------------------------------------
LANG_EXTENSIONS: dict[str, list[str]] = {
    "Python": [".py"],
    "Rust": [".rs"],
    "TypeScript": [".ts", ".tsx"],
    "JavaScript": [".js", ".jsx", ".mjs"],
    "Nix": [".nix"],
    "Go": [".go"],
    "Solidity": [".sol"],
    "Shell": [".sh"],
    "YAML": [".yaml", ".yml"],
    "TOML": [".toml"],
    "JSON": [".json"],
    "Markdown": [".md"],
    "CSS": [".css"],
    "HTML": [".html"],
    "C": [".c", ".h"],
    "C++": [".cpp", ".hpp", ".cc", ".hh"],
    "Java": [".java"],
    "Zig": [".zig"],
    "Svelte": [".svelte"],
}

EXT_TO_LANG: dict[str, str] = {ext: lang for lang, exts in LANG_EXTENSIONS.items() for ext in exts}

# ---------------------------------------------------------------------------
# Skip / security constants
# ---------------------------------------------------------------------------
SKIP_DIRS = {
    ".git", "node_modules", ".venv", "venv", "target", "dist", "build",
    "__pycache__", ".cache", ".nix-profile", "result", ".pytest_cache",
    ".nix-pip", ".archive", ".next",
}

# Vendored dependencies are *tracked on purpose* (Go vendoring, air-gapped builds), so
# git-tracking alone will not exclude them. They are a deliberate architectural choice —
# reported as a characteristic, never counted as authored code and never penalised.
VENDOR_DIRS = {"vendor", "third_party", "thirdparty", "external", "bower_components", "Godeps"}

# Build/report output that is committed. Not authored, not vendored.
GENERATED_DIRS = {
    "htmlcov", "coverage", "site", "_site", "storybook-static", "out",
    ".tox", ".mypy_cache", ".direnv", "__generated__",
}

# Generated by name, not by location. `vmlinux.h` is 139K lines of kernel BTF types
# emitted by bpftool and committed next to a ~200-line eBPF probe; counting it as
# authored C made owasaka read as a 177K-line C project.
GENERATED_FILES = re.compile(
    r'(^|/)(vmlinux\.h|.*\.pb\.go|.*_pb2\.pyi?|.*_pb2_grpc\.py|.*\.generated\..*|'
    r'.*_generated\.(go|rs|ts)|bindings\.rs|schema\.graphql\.d\.ts)$'
)

DOC_EXTS = {".md", ".mdx", ".rst", ".adoc", ".txt"}
CONFIG_EXTS = {".yaml", ".yml", ".toml", ".json", ".nix", ".ini", ".cfg"}

# Anything outside this set is not counted at all — binaries, images and fonts have no
# meaningful line count, and lockfiles are not authorship.
KNOWN_TEXT_EXTS = set(EXT_TO_LANG) | DOC_EXTS | CONFIG_EXTS

MAX_FILES_PER_REPO = 80_000  # safety cap for huge data repos

# Findings are only meaningful with an entropy gate: the old pattern matched any schema
# field literally named "api_key", which made repos full of tool definitions (securellm-mcp)
# and security modules (nixos) score 0. Real secrets look random; field names do not.
# Patterns are scoped to the languages where they actually mean something. The old
# `\b(eval|exec)\s*\(` matched `regex.exec()` and `db.exec()` — idiomatic JS and SQLite —
# and `debugger` matched the word appearing in Nix config. A finding must be a finding
# in *that* language, or the scanner just measures repo size.
PY_EXTS = {".py"}
JS_EXTS = {".js", ".jsx", ".mjs", ".ts", ".tsx"}
SECRET_EXTS = {".py", ".rs", ".ts", ".tsx", ".js", ".jsx", ".mjs", ".go", ".sh"}

SECURITY_PATTERNS: dict[str, tuple[re.Pattern, set[str]]] = {
    # `(?<![\w.])` prevents matching method calls like `.exec(` / `foo.eval(`
    "hardcoded_secret": (
        re.compile(
            r'(?i)(api[_-]?key|secret[_-]?key|password|token)\s*[=:]\s*["\']([A-Za-z0-9+/=_-]{20,})["\']'
        ),
        SECRET_EXTS,
    ),
    "unsafe_eval_py": (re.compile(r'(?<![\w.])(?:eval|exec)\s*\('), PY_EXTS),
    "unsafe_eval_js": (re.compile(r'(?<![\w.])eval\s*\('), JS_EXTS),
    "shell_true": (re.compile(r'subprocess\.\w+\([^)]*shell\s*=\s*True'), PY_EXTS),
    "debug_left_py": (re.compile(r'(?<![\w.])(?:pdb\.set_trace|breakpoint)\s*\('), PY_EXTS),
    "debug_left_js": (re.compile(r'^\s*debugger\s*;?\s*$', re.MULTILINE), JS_EXTS),
}

# Security tooling whose presence is itself hardening evidence. nixos ships 294 modules
# that configure these; scoring it 0 because the word "password" appears in them was the
# exact inversion this rubric exists to remove.
SECURITY_TOOLING = (
    "apparmor", "seccomp", "wazuh", "suricata", "fail2ban", "auditd", "lynis",
    "sops", "agenix", "vault", "opensearch", "yara", "clamav", "firejail", "selinux",
)

# Paths where a "secret-looking" literal is a fixture, schema, or example by definition.
SECURITY_ALLOWLIST = re.compile(
    r'(^|/)(tests?|fixtures?|examples?|mocks?|schemas?|docs?|\.github)(/|$)|'
    r'(test_|_test\.|\.test\.|\.spec\.|\.example|\.sample|template)',
    re.IGNORECASE,
)

# Positive security posture signals. Presence of these is evidence of deliberate
# hardening — the inverse of the old "count regex hits and subtract" model.
SECURITY_POSTURE_FILES = {
    "SECURITY.md": 12.0,
    "THREAT_MODEL.md": 12.0,
    ".sops.yaml": 10.0,
    ".sops.yml": 10.0,
    "secrets.nix": 8.0,
    ".gitleaks.toml": 8.0,
    "cosign.pub": 10.0,
}
SECURITY_POSTURE_DIRS = {
    ".chain": 12.0,       # signature / provenance chain (adr-ledger)
    "policies": 8.0,      # OPA / Rego
    "sbom": 10.0,
}

# Operability signals — the difference between "runs on my machine" and "stays up".
OPERABILITY_MARKERS = {
    "healthcheck": 18.0,
    "structured_logging": 16.0,
    "metrics_endpoint": 18.0,
    "tracing": 14.0,
    "runbook": 16.0,
    "graceful_shutdown": 10.0,
    "restart_policy": 8.0,
}

# Shannon-entropy floor for treating a matched literal as a plausible real secret.
SECRET_ENTROPY_MIN: float = 3.2


# ---------------------------------------------------------------------------
# Data classes
# ---------------------------------------------------------------------------
@dataclass
class RepoMetricsSnapshot:
    """Full metrics snapshot for one repository."""

    name: str
    path: str
    collected_at: str = ""

    # code
    total_files: int = 0
    total_loc: int = 0          # authored only — see loc_* buckets below
    languages: dict[str, dict[str, int]] = field(default_factory=dict)
    primary_language: str = ""

    # LoC buckets (concept A: measurement). total_loc == loc_authored; the rest are
    # reported separately so vendored deps never inflate an authorship claim.
    loc_authored: int = 0
    loc_vendored: int = 0
    loc_generated: int = 0
    loc_docs: int = 0
    loc_config: int = 0

    # classification (concepts B + C)
    archetype: str = "unknown"
    stack_layer: str = "unknown"

    # git
    git: dict[str, Any] = field(default_factory=dict)

    # deps
    dependencies: list[str] = field(default_factory=list)
    dep_count: int = 0

    # security
    security_findings: list[dict[str, Any]] = field(default_factory=list)
    security_score: float = 100.0

    # quality
    has_tests: bool = False
    test_files: int = 0
    has_ci: bool = False
    has_readme: bool = False
    has_docs: bool = False
    has_flake: bool = False

    # architecture (new)
    frameworks: list[str] = field(default_factory=list)
    entrypoints: list[str] = field(default_factory=list)
    infrastructure: list[str] = field(default_factory=list)
    databases: list[str] = field(default_factory=list)
    apis: list[str] = field(default_factory=list)
    
    # complexity (new)
    max_depth: int = 0
    avg_file_size: int = 0
    largest_files: list[dict[str, Any]] = field(default_factory=list)

    # signals feeding the rubric (concept D)
    release: dict[str, Any] = field(default_factory=dict)
    reproducibility: dict[str, Any] = field(default_factory=dict)
    interface: dict[str, Any] = field(default_factory=dict)
    operability: dict[str, Any] = field(default_factory=dict)
    security_posture: dict[str, Any] = field(default_factory=dict)
    knowledge: dict[str, Any] = field(default_factory=dict)
    delivery: dict[str, Any] = field(default_factory=dict)

    # visibility — a private repo has no observable adoption. That is a publishing
    # decision, not a quality signal, so adoption is scored N/A rather than zero.
    is_public: bool = False
    adoption: dict[str, Any] = field(default_factory=dict)

    # centrality is cross-repo, so it is filled in a second pass over all snapshots
    dependents: list[str] = field(default_factory=list)
    centrality_score: float | None = None

    # derived
    health_score: float = 0.0
    health: dict[str, Any] = field(default_factory=dict)
    status: str = "unknown"

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


# ---------------------------------------------------------------------------
# Collector
# ---------------------------------------------------------------------------
class MetricsCollector:
    """Zero-token metrics collector.  git + fs + regex, no LLM."""

    def __init__(self, arch_path: str | None = None):
        self.arch_path = Path(arch_path or os.getenv("CEREBRO_ARCH_PATH", str(Path.home() / "master")))
        self.metrics_dir = self.arch_path / "cerebro" / "data" / "metrics"
        self.metrics_dir.mkdir(parents=True, exist_ok=True)
        self._gh_meta_cache: dict[str, Any] | None = None

    # ------------------------------------------------------------------
    # Discovery
    # ------------------------------------------------------------------
    # Names that are vendor / skill sub-repos — skip them
    SKIP_REPO_NAMES = {"ux-agents", "forge-std", "sdk-core"}

    def discover_repos(self) -> list[Path]:
        """Discover git repos up to 2 levels deep under arch_path, deduplicated."""
        seen: set = set()          # resolved paths already added
        repos: list[Path] = []
        skip_top = {"scripts", "docs", "skills"}

        def _add(p: Path) -> None:
            resolved = p.resolve()
            if resolved in seen or p.name in self.SKIP_REPO_NAMES:
                return
            seen.add(resolved)
            repos.append(p)

        for top in sorted(self.arch_path.iterdir()):
            if not top.is_dir() or top.name.startswith(".") or top.name in skip_top:
                continue
            if (top / ".git").exists():
                _add(top)

            try:
                for sub in sorted(top.iterdir()):
                    if not sub.is_dir() or sub.name.startswith(".") or sub.name in SKIP_DIRS:
                        continue
                    if (sub / ".git").exists():
                        _add(sub)
                    # two levels deep (e.g. org/repo/services/*)
                    try:
                        for subsub in sorted(sub.iterdir()):
                            if not subsub.is_dir() or subsub.name.startswith(".") or subsub.name in SKIP_DIRS:
                                continue
                            if (subsub / ".git").exists():
                                _add(subsub)
                    except (PermissionError, OSError):
                        pass
            except (PermissionError, OSError):
                pass

        return repos

    # ------------------------------------------------------------------
    # Bulk / single collection
    # ------------------------------------------------------------------
    def collect_all(self) -> list[RepoMetricsSnapshot]:
        repos = self.discover_repos()
        logger.info("MetricsCollector: discovered %d repos", len(repos))
        results: list[RepoMetricsSnapshot] = []
        for repo_path in repos:
            try:
                results.append(self.collect_repo(repo_path))
            except Exception as e:
                logger.error("  ✗ %s: %s", repo_path.name, e)

        # Second pass: centrality is a property of the graph, not of a single repo.
        self._score_centrality(results)
        for snapshot in results:
            health = self._calculate_health(snapshot)
            snapshot.health = health.to_dict()
            snapshot.health_score = health.score
            logger.info(
                "  ✓ %-22s %-16s LoC=%-7d health=%.0f",
                snapshot.name, snapshot.archetype, snapshot.total_loc, snapshot.health_score,
            )

        self._save_snapshot(results)
        return results

    def collect_repo(self, repo_path: Path) -> RepoMetricsSnapshot:
        snapshot = RepoMetricsSnapshot(
            name=repo_path.name,
            path=str(repo_path),
            collected_at=datetime.now(UTC).isoformat(),
        )
        self._collect_code_metrics(repo_path, snapshot)
        self._collect_git_metrics(repo_path, snapshot)
        self._collect_dependencies(repo_path, snapshot)
        self._collect_quality(repo_path, snapshot)
        self._collect_security(repo_path, snapshot)
        self._collect_architecture(repo_path, snapshot)
        self._collect_interface(repo_path, snapshot)

        # Classification must run after code/git/deps/interface so it can see their
        # signals, and before scoring, which is weighted by the resulting profile.
        self._classify(repo_path, snapshot)

        self._collect_delivery(repo_path, snapshot)
        self._collect_release(repo_path, snapshot)
        self._collect_reproducibility(repo_path, snapshot)
        self._collect_operability(repo_path, snapshot)
        self._collect_knowledge(repo_path, snapshot)
        self._collect_adoption(repo_path, snapshot)

        snapshot.status = self._determine_status(snapshot)

        # Provisional score so single-repo callers (watcher, `metrics report`) get a
        # usable number. collect_all() recomputes it once centrality is known; until
        # then centrality is None, i.e. N/A rather than a zero.
        health = self._calculate_health(snapshot)
        snapshot.health = health.to_dict()
        snapshot.health_score = health.score
        return snapshot

    # ------------------------------------------------------------------
    # Centrality — cross-repo, so it needs every snapshot to exist first
    # ------------------------------------------------------------------
    def _score_centrality(self, snapshots: list[RepoMetricsSnapshot]) -> None:
        """Blast radius: how much of the ecosystem leans on this repo.

        This is the clearest seniority signal in the whole rubric and was entirely
        unmeasured — owning the component 28 services depend on is a different kind
        of work from owning a leaf.
        """
        names = {s.name for s in snapshots}
        dependents: dict[str, set[str]] = {n: set() for n in names}

        # Orchestration: a service named in the master compose is depended upon.
        compose_refs: set[str] = set()
        for compose in (
            self.arch_path / "deploy" / "docker-compose.master.yml",
            Path.home() / "Projects" / "master" / "deploy" / "docker-compose.master.yml",
        ):
            if compose.exists():
                try:
                    blob = compose.read_text(errors="ignore")
                    compose_refs |= {n for n in names if re.search(rf'\b{re.escape(n)}\b', blob)}
                except OSError:
                    pass

        for snap in snapshots:
            src = Path(snap.path)
            # A flake *input* pointing at a sibling repo is a hard dependency edge.
            # Matching the bare name anywhere in the file is far too loose: it makes
            # `nixos-hardware` an edge to `nixos` and `cerebro-reranker` an edge to
            # `cerebro`, which flattened five unrelated repos to a perfect score.
            flake = src / "flake.nix"
            if not flake.exists():
                continue
            try:
                text = flake.read_text(errors="ignore")
            except OSError:
                continue

            referenced: set[str] = set()
            for m in re.finditer(r'url\s*=\s*"([^"]+)"', text):
                url = m.group(1)
                tail = url.rstrip("/").split("/")[-1].split("?")[0]
                if tail in names:
                    referenced.add(tail)
            for other in referenced:
                if other != snap.name:
                    dependents[other].add(snap.name)

        for snap in snapshots:
            deps = dependents[snap.name]
            score = min(70.0, len(deps) * 14.0)
            if snap.name in compose_refs:
                score += 30.0  # part of the integrated platform, not a standalone repo
            snap.dependents = sorted(deps)
            snap.centrality_score = round(min(100.0, score), 1)

    # ------------------------------------------------------------------
    # Code metrics (filesystem)
    # ------------------------------------------------------------------
    @staticmethod
    def _bucket_for(rel_parts: tuple[str, ...], ext: str) -> str:
        """Classify a file into an LoC bucket (concept A).

        Order matters: vendored and generated win over language, because a vendored
        Go file is a dependency regardless of it being Go.
        """
        if any(p in VENDOR_DIRS for p in rel_parts):
            return "vendored"
        if any(p in GENERATED_DIRS for p in rel_parts) or GENERATED_FILES.search("/".join(rel_parts)):
            return "generated"
        if ext in DOC_EXTS:
            return "docs"
        if ext in CONFIG_EXTS:
            return "config"
        return "authored"

    def _collect_code_metrics(self, repo_path: Path, snapshot: RepoMetricsSnapshot) -> None:
        lang_stats: dict[str, dict[str, int]] = defaultdict(lambda: {"files": 0, "lines": 0})
        buckets: dict[str, int] = defaultdict(int)

        for file_path in self._iter_files(repo_path):
            if snapshot.total_files >= MAX_FILES_PER_REPO:
                break
            snapshot.total_files += 1
            ext = file_path.suffix.lower()
            try:
                rel_parts = file_path.relative_to(repo_path).parts
            except ValueError:
                continue

            # Only count text we can actually attribute. Reading a .png with
            # errors="ignore" and calling splitlines() yields tens of thousands of
            # "lines" of decoded binary — that alone accounted for 119K of the wiki's
            # supposed 123K authored lines.
            if ext not in KNOWN_TEXT_EXTS:
                continue

            bucket = self._bucket_for(rel_parts, ext)
            try:
                lines = len(file_path.read_text(errors="ignore").splitlines())
            except (OSError, UnicodeDecodeError):
                continue
            buckets[bucket] += lines

            # Language stats describe authored code only. Counting vendored Go as the
            # repo's primary language is how owasaka came out as a 1.36M-line Go project.
            if bucket == "authored" and ext in EXT_TO_LANG:
                lang = EXT_TO_LANG[ext]
                lang_stats[lang]["files"] += 1
                lang_stats[lang]["lines"] += lines

        snapshot.loc_authored = buckets["authored"]
        snapshot.loc_vendored = buckets["vendored"]
        snapshot.loc_generated = buckets["generated"]
        snapshot.loc_docs = buckets["docs"]
        snapshot.loc_config = buckets["config"]
        snapshot.total_loc = buckets["authored"]

        snapshot.languages = dict(lang_stats)
        if lang_stats:
            snapshot.primary_language = max(lang_stats, key=lambda k: lang_stats[k]["lines"])

    def _iter_files(self, path: Path, depth: int = 0) -> Iterator[Path]:
        """Enumerate repo files, preferring git's index over a filesystem walk.

        `git ls-files` gives exactly the tracked set, which excludes everything
        .gitignore already handles (build output, virtualenvs, node_modules) without
        needing to guess at directory names. Falls back to walking for non-git dirs.
        """
        if depth == 0 and (path / ".git").exists():
            tracked = self._git_output(path, ["ls-files", "-z"])
            if tracked:
                for rel in tracked.split("\0"):
                    if not rel:
                        continue
                    parts = Path(rel).parts
                    if any(p in SKIP_DIRS for p in parts):
                        continue
                    f = path / rel
                    try:
                        if f.is_file() and f.stat().st_size < 5_000_000:
                            yield f
                    except OSError:
                        continue
                return

        if depth > 7:
            return
        try:
            for item in path.iterdir():
                if item.name.startswith(".") or item.name in SKIP_DIRS:
                    continue
                if item.is_file():
                    try:
                        if item.stat().st_size < 5_000_000:  # skip files > 5 MB
                            yield item
                    except OSError:
                        pass
                elif item.is_dir():
                    yield from self._iter_files(item, depth + 1)
        except PermissionError:
            pass

    # ------------------------------------------------------------------
    # Git metrics
    # ------------------------------------------------------------------
    def _collect_git_metrics(self, repo_path: Path, snapshot: RepoMetricsSnapshot) -> None:
        if not (repo_path / ".git").exists():
            snapshot.git = {"error": "not a git repo"}
            return

        git: dict[str, Any] = {}
        git["total_commits"] = self._git_int(repo_path, ["rev-list", "--count", "HEAD"])
        git["commits_30d"] = self._git_int(repo_path, ["rev-list", "--count", "--after=30 days ago", "HEAD"])
        git["commits_90d"] = self._git_int(repo_path, ["rev-list", "--count", "--after=90 days ago", "HEAD"])

        # contributors
        shortlog = self._git_output(repo_path, ["shortlog", "-sn", "--no-merges"])
        git["contributors"] = len([ln for ln in shortlog.splitlines() if ln.strip()])

        # branches / tags
        git["branches"] = len([ln for ln in self._git_output(repo_path, ["branch", "--list"]).splitlines() if ln.strip()])
        git["tags"] = len([ln for ln in self._git_output(repo_path, ["tag", "--list"]).splitlines() if ln.strip()])

        # last commit info
        last = self._git_output(repo_path, ["log", "-1", "--format=%H|%an|%ai|%s"])
        if last and "|" in last:
            parts = last.strip().split("|", 3)
            if len(parts) >= 4:
                git["last_commit_hash"] = parts[0][:12]
                git["last_commit_author"] = parts[1]
                git["last_commit_date"] = parts[2]
                git["last_commit_message"] = parts[3][:120]

        # top contributors
        git["top_contributors"] = []
        for line in shortlog.splitlines()[:5]:
            m = re.match(r"\s*(\d+)\s+(.+)", line.strip())
            if m:
                git["top_contributors"].append({"name": m.group(2).strip(), "commits": int(m.group(1))})

        snapshot.git = git

    # ------------------------------------------------------------------
    # Dependencies
    # ------------------------------------------------------------------
    def _collect_dependencies(self, repo_path: Path, snapshot: RepoMetricsSnapshot) -> None:
        deps: list[str] = []

        # pyproject.toml (Poetry)
        pyproject = repo_path / "pyproject.toml"
        if pyproject.exists():
            try:
                data = tomllib.loads(pyproject.read_text())
                for name in data.get("tool", {}).get("poetry", {}).get("dependencies", {}):
                    if name != "python":
                        deps.append(f"py:{name}")
            except Exception:
                pass

        # package.json
        pkg = repo_path / "package.json"
        if pkg.exists():
            try:
                data = json.loads(pkg.read_text())
                for name in data.get("dependencies", {}):
                    deps.append(f"npm:{name}")
                for name in data.get("devDependencies", {}):
                    deps.append(f"npm-dev:{name}")
            except Exception:
                pass

        # Cargo.toml
        cargo = repo_path / "Cargo.toml"
        if cargo.exists():
            try:
                content = cargo.read_text()
                in_deps = False
                for line in content.splitlines():
                    stripped = line.strip()
                    if stripped == "[dependencies]":
                        in_deps = True
                        continue
                    if stripped.startswith("[") and in_deps:
                        break
                    if in_deps:
                        m = re.match(r'^([\w-]+)\s*=', stripped)
                        if m:
                            deps.append(f"cargo:{m.group(1)}")
            except Exception:
                pass

        # go.mod
        gomod = repo_path / "go.mod"
        if gomod.exists():
            try:
                in_require = False
                for line in gomod.read_text().splitlines():
                    stripped = line.strip()
                    if stripped.startswith("require"):
                        in_require = True
                        continue
                    if in_require and stripped == ")":
                        in_require = False
                        continue
                    if in_require:
                        m = re.match(r"([\w./\-]+)\s+v", stripped)
                        if m:
                            deps.append(f"go:{m.group(1)}")
            except Exception:
                pass

        snapshot.dependencies = deps
        snapshot.dep_count = len(deps)

    # ------------------------------------------------------------------
    # Security scan
    # ------------------------------------------------------------------
    @staticmethod
    def _shannon_entropy(s: str) -> float:
        if not s:
            return 0.0
        counts = Counter(s)
        n = len(s)
        return -sum((c / n) * math.log2(c / n) for c in counts.values())

    def _collect_security(self, repo_path: Path, snapshot: RepoMetricsSnapshot) -> None:
        """Security posture = positive hardening evidence, minus *credible* findings.

        The previous model was `100 - hits * 10` over a regex that matched any field
        literally named `api_key`. That inverted the signal: securellm-mcp scored 0
        because it declares 62 tool schemas, and nixos scored 10 because it ships 294
        hardening modules that name the things they harden. Findings now require an
        entropy gate and skip fixture/schema/example paths, and posture is driven by
        what the repo actively does — SECURITY.md, sops, signing chains, SBOM, OPA.
        """
        findings: list[dict[str, Any]] = []
        scanned = 0
        tooling: set[str] = set()

        for file_path in self._iter_files(repo_path):
            if scanned >= 15_000:
                break
            ext = file_path.suffix.lower()
            rel = str(file_path.relative_to(repo_path))

            # Configuring a security tool is hardening evidence, wherever it lives.
            low_rel = rel.lower()
            tooling |= {t for t in SECURITY_TOOLING if t in low_rel}

            applicable = {n: p for n, (p, exts) in SECURITY_PATTERNS.items() if ext in exts}
            if not applicable or SECURITY_ALLOWLIST.search(rel):
                continue
            scanned += 1
            try:
                content = file_path.read_text(errors="ignore")
            except (OSError, UnicodeDecodeError):
                continue

            for pname, pat in applicable.items():
                m = pat.search(content)
                if not m:
                    continue
                # For secret-shaped matches, require the literal to actually look random.
                if pname == "hardcoded_secret":
                    literal = m.group(2) if m.lastindex and m.lastindex >= 2 else ""
                    if self._shannon_entropy(literal) < SECRET_ENTROPY_MIN:
                        continue
                findings.append({
                    "type": pname,
                    "file": rel,
                    "line": content[: m.start()].count("\n") + 1,
                })

        # Positive posture signals
        posture: dict[str, Any] = {"signals": [], "points": 0.0}
        for fname, pts in SECURITY_POSTURE_FILES.items():
            if (repo_path / fname).exists():
                posture["signals"].append(fname)
                posture["points"] += pts
        for dname, pts in SECURITY_POSTURE_DIRS.items():
            if (repo_path / dname).is_dir():
                posture["signals"].append(f"{dname}/")
                posture["points"] += pts
        if tooling:
            posture["signals"].extend(sorted(tooling))
            posture["points"] += min(30.0, len(tooling) * 6.0)
            posture["tooling"] = sorted(tooling)

        # Supply-chain evidence lives in CI, not at the repo root.
        wf_dir = repo_path / ".github" / "workflows"
        if wf_dir.is_dir():
            try:
                wf_blob = " ".join(
                    p.read_text(errors="ignore").lower()
                    for p in wf_dir.glob("*.y*ml")
                )
            except OSError:
                wf_blob = ""
            for needle, label, pts in (
                ("gitleaks", "secret-scan", 10.0),
                ("trufflehog", "secret-scan", 10.0),
                ("syft", "sbom", 10.0),
                ("cyclonedx", "sbom", 10.0),
                ("cosign", "artifact-signing", 10.0),
                ("trivy", "cve-scan", 8.0),
                ("semgrep", "sast", 8.0),
                ("lynis", "hardening-audit", 12.0),
            ):
                if needle in wf_blob and label not in posture["signals"]:
                    posture["signals"].append(label)
                    posture["points"] += pts

        posture["findings"] = len(findings)
        snapshot.security_findings = findings
        snapshot.security_posture = posture
        # Baseline 45 so a repo with no explicit posture is "unproven", not "insecure".
        snapshot.security_score = round(
            max(0.0, min(100.0, 45.0 + posture["points"] - len(findings) * 6.0)), 1
        )

    # ------------------------------------------------------------------
    # Quality indicators
    # ------------------------------------------------------------------
    def _collect_quality(self, repo_path: Path, snapshot: RepoMetricsSnapshot) -> None:
        snapshot.has_readme = any((repo_path / f).exists() for f in ["README.md", "README.rst", "README"])
        snapshot.has_docs = (repo_path / "docs").exists()
        snapshot.has_flake = (repo_path / "flake.nix").exists()
        snapshot.has_ci = (
            (repo_path / ".github" / "workflows").exists()
            or (repo_path / ".gitlab-ci.yml").exists()
            or (repo_path / "Jenkinsfile").exists()
        )

        # Tests are counted wherever they live. Requiring a top-level tests/ directory
        # missed every co-located suite (`Foo.test.ts`, `foo_test.go`, `#[cfg(test)]`),
        # which read as "no tests at all" for repos that are in fact well covered.
        count = 0
        for f in self._iter_files(repo_path):
            rel = f.relative_to(repo_path).as_posix()
            if re.search(r'(^|/)(tests?|__tests__|spec)(/|$)', rel) or \
               re.search(r'(^|/)test_[^/]+$|_test\.[a-z]+$|\.test\.[a-z]+$|\.spec\.[a-z]+$', rel):
                count += 1
                if count >= 5000:
                    break

        snapshot.test_files = count
        snapshot.has_tests = count > 0

    # ------------------------------------------------------------------
    # Architecture (True Knowledge)
    # ------------------------------------------------------------------
    def _collect_architecture(self, repo_path: Path, snapshot: RepoMetricsSnapshot) -> None:
        frameworks = set()
        entrypoints = set()
        infrastructure = set()
        databases = set()
        apis = set()
        
        file_sizes = []
        max_depth = 0
        
        # Determine from dependencies
        deps = set(snapshot.dependencies)
        for dep in deps:
            if "fastapi" in dep or "starlette" in dep: frameworks.add("FastAPI")
            if "django" in dep: frameworks.add("Django")
            if "flask" in dep: frameworks.add("Flask")
            if "react" in dep: frameworks.add("React")
            if "next" in dep: frameworks.add("Next.js")
            if "vue" in dep: frameworks.add("Vue")
            if "svelte" in dep: frameworks.add("Svelte")
            if "sqlalchemy" in dep or "prisma" in dep or "diesel" in dep or "gorm" in dep:
                databases.add("ORM Detected")
        
        # Determine from files
        for f in self._iter_files(repo_path):
            try:
                stat = f.stat()
                file_sizes.append({"path": str(f.relative_to(repo_path)), "size": stat.st_size})
            except OSError:
                continue
            
            parts = f.relative_to(repo_path).parts
            max_depth = max(max_depth, len(parts))
            
            name = f.name.lower()
            if name in ["dockerfile", "docker-compose.yml", "docker-compose.yaml"]:
                infrastructure.add("Docker")
            elif name in ["makefile", "justfile"]:
                entrypoints.add(f.name)
            elif name in ["main.py", "manage.py", "index.ts", "main.go"]:
                entrypoints.add(f.name)
            elif name == "flake.nix":
                infrastructure.add("Nix")
            elif f.suffix in [".tf"]:
                infrastructure.add("Terraform")
            elif "k8s" in parts or "kubernetes" in parts:
                infrastructure.add("Kubernetes")
                
            if name in ["openapi.yaml", "openapi.json", "swagger.json", "swagger.yaml"]:
                apis.add("OpenAPI/Swagger")
            elif f.suffix == ".proto":
                apis.add("gRPC")
            elif f.suffix == ".graphql":
                apis.add("GraphQL")
                
            if "migrations" in parts or "alembic" in parts:
                databases.add("Migrations")
            if name == "schema.sql":
                databases.add("Raw SQL Schema")

        file_sizes.sort(key=lambda x: x["size"], reverse=True)
        
        snapshot.frameworks = sorted(list(frameworks))
        snapshot.entrypoints = sorted(list(entrypoints))
        snapshot.infrastructure = sorted(list(infrastructure))
        snapshot.databases = sorted(list(databases))
        snapshot.apis = sorted(list(apis))
        
        snapshot.max_depth = max_depth
        snapshot.avg_file_size = sum(x["size"] for x in file_sizes) // len(file_sizes) if file_sizes else 0
        snapshot.largest_files = file_sizes[:5]

    # ------------------------------------------------------------------
    # Health / status
    # ------------------------------------------------------------------
    # ------------------------------------------------------------------
    # Rubric signals
    # ------------------------------------------------------------------
    def _collect_delivery(self, repo_path: Path, snapshot: RepoMetricsSnapshot) -> None:
        """Sustained delivery: how much of the repo's life had real work in it.

        Replaces raw recency. A repo with 12,744 commits spread over years is a
        sustained platform investment; the old activity term scored it 0 for not
        having been touched in the last 30 days.
        """
        months = self._git_output(repo_path, ["log", "--format=%ad", "--date=format:%Y-%m"])
        stamps = [m for m in months.split("\n") if m.strip()]
        if not stamps:
            snapshot.delivery = {"score": 0.0, "active_months": 0, "lifespan_months": 0}
            return

        active = sorted(set(stamps))
        first, last = active[0], active[-1]
        fy, fm = (int(x) for x in first.split("-"))
        ly, lm = (int(x) for x in last.split("-"))
        lifespan = max(1, (ly - fy) * 12 + (lm - fm) + 1)
        consistency = len(active) / lifespan

        score = min(60.0, consistency * 60.0)          # rhythm
        score += min(25.0, len(active) * 1.2)          # accumulated months of work
        score += min(15.0, len(stamps) / 100.0)        # raw volume, heavily damped

        snapshot.delivery = {
            "score": round(min(100.0, score), 1),
            "active_months": len(active),
            "lifespan_months": lifespan,
            "consistency": round(consistency, 3),
            "first_commit_month": first,
            "last_commit_month": last,
        }

    def _collect_release(self, repo_path: Path, snapshot: RepoMetricsSnapshot) -> None:
        tags = self._git_output(repo_path, ["tag", "--list"]).split()
        semver = [t for t in tags if re.match(r"^v?\d+\.\d+\.\d+", t)]
        changelog = any((repo_path / n).exists() for n in ("CHANGELOG.md", "CHANGELOG", "CHANGES.md"))
        wf_dir = repo_path / ".github" / "workflows"
        release_wf = wf_dir.is_dir() and any("release" in p.name.lower() for p in wf_dir.glob("*.y*ml"))

        score = 0.0
        score += min(40.0, len(tags) * 8.0)
        if semver:
            score += 25.0
        if changelog:
            score += 20.0
        if release_wf:
            score += 15.0

        snapshot.release = {
            "score": round(min(100.0, score), 1),
            "tags": len(tags),
            "semver_tags": len(semver),
            "has_changelog": changelog,
            "has_release_workflow": release_wf,
        }

    def _collect_reproducibility(self, repo_path: Path, snapshot: RepoMetricsSnapshot) -> None:
        """Depth of the build contract, not merely `flake.nix exists`.

        32 of 33 repos here ship a flake; as a boolean that fact carries one bit and
        the ecosystem's single strongest differentiator disappears into it.
        """
        flake = repo_path / "flake.nix"
        if not flake.exists():
            lock = any((repo_path / n).exists() for n in
                       ("package-lock.json", "pnpm-lock.yaml", "Cargo.lock", "poetry.lock", "uv.lock"))
            snapshot.reproducibility = {"score": 25.0 if lock else 0.0, "has_flake": False, "lockfile": lock}
            return

        try:
            text = flake.read_text(errors="ignore")
        except OSError:
            text = ""

        outputs = [k for k in ("packages", "devShells", "checks", "apps", "overlays", "nixosModules")
                   if re.search(rf"\b{k}\b\s*=", text)]

        wf_dir = repo_path / ".github" / "workflows"
        wf_blob = ""
        if wf_dir.is_dir():
            try:
                wf_blob = " ".join(p.read_text(errors="ignore").lower() for p in wf_dir.glob("*.y*ml"))
            except OSError:
                pass
        flake_check_ci = "nix flake check" in wf_blob
        test_in_ci = any(w in wf_blob for w in ("pytest", "cargo test", "npm test", "pnpm test", "go test", "nix flake check"))

        lock = repo_path / "flake.lock"
        lock_age_days = None
        if lock.exists():
            out = self._git_output(repo_path, ["log", "-1", "--format=%ct", "--", "flake.lock"]).strip()
            if out.isdigit():
                lock_age_days = int((datetime.now(UTC).timestamp() - int(out)) / 86400)

        score = 35.0                                   # having a flake at all
        score += min(30.0, len(outputs) * 6.0)         # what it actually exposes
        if flake_check_ci:
            score += 20.0
        if lock_age_days is not None and lock_age_days < 60:
            score += 15.0

        snapshot.reproducibility = {
            "score": round(min(100.0, score), 1),
            "has_flake": True,
            "outputs": outputs,
            "flake_check_in_ci": flake_check_ci,
            "test_in_ci": test_in_ci,
            "lock_age_days": lock_age_days,
        }

    def _collect_interface(self, repo_path: Path, snapshot: RepoMetricsSnapshot) -> None:
        """Delivered capability: endpoints, tools, modules, commands, crates."""
        counts = {"endpoints": 0, "mcp_tools": 0, "modules": 0, "cli_commands": 0, "workspace_members": 0}
        has_integration = False

        for f in self._iter_files(repo_path):
            rel = str(f.relative_to(repo_path))
            if "integration" in rel.lower() and SECURITY_ALLOWLIST.search(rel):
                has_integration = True
            ext = f.suffix.lower()
            if ext not in {".py", ".rs", ".ts", ".tsx", ".go", ".nix"}:
                continue
            try:
                text = f.read_text(errors="ignore")
            except (OSError, UnicodeDecodeError):
                continue
            counts["endpoints"] += len(re.findall(
                r'@(?:app|router)\.(?:get|post|put|delete|patch)\(|'
                r'\.route\(\s*["\']|HttpServer::|axum::Router', text))
            counts["cli_commands"] += len(re.findall(r'@(?:app|cli)\.command\(|#\[command\(', text))
            if rel.startswith(("src/tools/", "tools/")) and ext in {".ts", ".py"}:
                counts["mcp_tools"] += 1
            if ext == ".nix" and (rel.startswith("modules/") or "/modules/" in rel):
                counts["modules"] += 1

        cargo = repo_path / "Cargo.toml"
        if cargo.exists():
            try:
                counts["workspace_members"] = len(re.findall(
                    r'^\s*"[^"]+",', cargo.read_text(errors="ignore"), re.MULTILINE))
            except OSError:
                pass

        surface = (counts["endpoints"] + counts["mcp_tools"] * 2 + counts["modules"]
                   + counts["cli_commands"] + counts["workspace_members"] * 3)
        snapshot.interface = {
            "score": round(min(100.0, surface * 1.6), 1),
            "has_integration_tests": has_integration,
            **counts,
        }

    def _collect_operability(self, repo_path: Path, snapshot: RepoMetricsSnapshot) -> None:
        """Evidence the thing is actually operated, not merely built.

        Keeping ~28 services up, solo, is harder than writing any one of them; that
        work leaves traces (health probes, restart policies, structured logs, runbooks)
        and none of them were previously measured.
        """
        found: list[str] = []
        blob_parts: list[str] = []
        for name in ("Dockerfile", "docker-compose.yml", "docker-compose.yaml", "Makefile", "justfile"):
            p = repo_path / name
            if p.exists():
                try:
                    blob_parts.append(p.read_text(errors="ignore").lower())
                except OSError:
                    pass
        blob = " ".join(blob_parts)

        if "healthcheck" in blob:
            found.append("healthcheck")
        if "restart:" in blob or "restart=" in blob:
            found.append("restart_policy")
        if any((repo_path / n).exists() for n in ("RUNBOOK.md", "docs/RUNBOOK.md", "OPERATIONS.md")):
            found.append("runbook")

        src_blob = ""
        for f in self._iter_files(repo_path):
            if f.suffix.lower() not in {".py", ".rs", ".ts", ".go"}:
                continue
            try:
                src_blob += f.read_text(errors="ignore")[:4000].lower()
            except (OSError, UnicodeDecodeError):
                continue
            if len(src_blob) > 400_000:
                break

        if any(k in src_blob for k in ("structlog", "tracing::", "slog", "pino", "zap.", "logrus")):
            found.append("structured_logging")
        if any(k in src_blob for k in ("prometheus", "/metrics", "metrics_endpoint")):
            found.append("metrics_endpoint")
        if any(k in src_blob for k in ("opentelemetry", "jaeger", "tracer")):
            found.append("tracing")
        if any(k in src_blob for k in ("graceful", "shutdown_signal", "sigterm")):
            found.append("graceful_shutdown")
        if "/health" in src_blob or "健康" in src_blob:
            if "healthcheck" not in found:
                found.append("healthcheck")

        score = sum(OPERABILITY_MARKERS.get(m, 0.0) for m in found)
        snapshot.operability = {"score": round(min(100.0, score), 1), "signals": found}

    def _collect_knowledge(self, repo_path: Path, snapshot: RepoMetricsSnapshot) -> None:
        adr_count = 0
        for d in ("adr", "docs/adr", "decisions", "docs/decisions"):
            p = repo_path / d
            if p.is_dir():
                adr_count += len([f for f in p.rglob("*.md")])
        has_arch = (repo_path / "ARCHITECTURE.md").exists()
        has_readme = snapshot.has_readme
        diagrams = 0
        for d in ("docs", "diagrams", "docs/diagrams"):
            p = repo_path / d
            if p.is_dir():
                diagrams += len(list(p.rglob("*.mmd"))) + len(list(p.rglob("*.svg")))

        score = 0.0
        if has_readme:
            score += 20.0
        if has_arch:
            score += 25.0
        score += min(30.0, adr_count * 2.0)
        score += min(15.0, diagrams * 3.0)
        if snapshot.loc_docs > 2000:
            score += 10.0

        snapshot.knowledge = {
            "score": round(min(100.0, score), 1),
            "adr_count": adr_count,
            "has_architecture_md": has_arch,
            "diagrams": diagrams,
        }

    def _collect_adoption(self, repo_path: Path, snapshot: RepoMetricsSnapshot) -> None:
        """External validation. Only meaningful for repos the world can see."""
        remote = self._git_output(repo_path, ["remote", "get-url", "origin"]).strip()
        meta = self._github_meta().get(repo_path.name, {})
        snapshot.is_public = bool(meta) or bool(meta.get("public")) if meta else False

        if not snapshot.is_public:
            snapshot.adoption = {
                "score": None,
                "reason": "private or unpublished — adoption not observable",
                "remote": bool(remote),
            }
            return

        stars = int(meta.get("stars", 0) or 0)
        forks = int(meta.get("forks", 0) or 0)
        contributors = max(0, snapshot.git.get("contributors", 0) - 1)

        score = min(60.0, stars * 3.0) + min(25.0, forks * 5.0) + min(15.0, contributors * 5.0)
        snapshot.adoption = {
            "score": round(min(100.0, score), 1),
            "stars": stars,
            "forks": forks,
            "external_contributors": contributors,
        }

    def _github_meta(self) -> dict[str, Any]:
        """Star/fork counts collected at build time by the portfolio site."""
        if self._gh_meta_cache is not None:
            return self._gh_meta_cache
        self._gh_meta_cache = {}
        candidate = self.arch_path / "projects-gui" / "portfolio" / "public" / "github-meta.json"
        if candidate.exists():
            try:
                raw = json.loads(candidate.read_text())
                repos = raw.get("repos", raw) if isinstance(raw, dict) else raw
                if isinstance(repos, dict):
                    self._gh_meta_cache = repos
                elif isinstance(repos, list):
                    self._gh_meta_cache = {r.get("name"): r for r in repos if isinstance(r, dict)}
            except Exception:
                pass
        return self._gh_meta_cache

    def _classify(self, repo_path: Path, snapshot: RepoMetricsSnapshot) -> None:
        filenames = {p.name for p in repo_path.iterdir()} if repo_path.is_dir() else set()
        archetype = classify_archetype(
            repo_path.name,
            deps=snapshot.dependencies,
            loc_authored=snapshot.loc_authored,
            loc_docs=snapshot.loc_docs,
            filenames=filenames,
            has_dockerfile="Dockerfile" in filenames,
            primary_language=snapshot.primary_language,
            total_commits=snapshot.git.get("total_commits", 0),
            has_ci=snapshot.has_ci,
            tags=snapshot.git.get("tags", 0),
            # Workspace/Cargo deps are often not parseable, so fall back to what the
            # source actually does: a repo serving HTTP routes is a service.
            endpoints=snapshot.interface.get("endpoints", 0),
            modules=snapshot.interface.get("modules", 0),
            cli_commands=snapshot.interface.get("cli_commands", 0),
        )
        snapshot.archetype = archetype.value
        snapshot.stack_layer = classify_layer(repo_path.name, archetype).value

    def _calculate_health(self, snapshot: RepoMetricsSnapshot) -> HealthResult:
        """Profile-weighted score over the dimensions that apply to this archetype.

        `None` means the dimension does not apply and is excluded from the weighted
        mean — as opposed to 0.0, which means it applies and the repo scores badly.
        Collapsing those two is what made a docs site look like a broken service.
        """
        archetype = Archetype(snapshot.archetype)
        layer = StackLayer(snapshot.stack_layer)

        dims: dict[Dimension, float | None] = {
            Dimension.CENTRALITY: snapshot.centrality_score,
            Dimension.SUSTAINED_DELIVERY: snapshot.delivery.get("score"),
            Dimension.RELEASE_DISCIPLINE: snapshot.release.get("score"),
            Dimension.REPRODUCIBILITY: snapshot.reproducibility.get("score"),
            Dimension.INTERFACE_SURFACE: snapshot.interface.get("score"),
            Dimension.TEST_DEPTH: self._test_depth_score(snapshot),
            Dimension.SECURITY_POSTURE: snapshot.security_score,
            Dimension.OPERABILITY: snapshot.operability.get("score"),
            Dimension.ARCHITECTURE_DEPTH: self._architecture_score(snapshot),
            Dimension.KNOWLEDGE_ARTIFACTS: snapshot.knowledge.get("score"),
            # A private repo has no observable stars or forks. That is a publishing
            # decision, not a quality signal, so it is N/A rather than zero.
            Dimension.ADOPTION: snapshot.adoption.get("score") if snapshot.is_public else None,
        }
        return score_repo(archetype, layer, dims)

    def _test_depth_score(self, snapshot: RepoMetricsSnapshot) -> float | None:
        """Ratio and kind of tests, not raw file count."""
        if snapshot.loc_authored < 200:
            return None  # too small for the ratio to mean anything
        if not snapshot.has_tests:
            return 0.0
        score = 0.0
        ratio = snapshot.test_files / max(1, snapshot.total_files)
        score += min(50.0, ratio * 250.0)
        if snapshot.interface.get("has_integration_tests"):
            score += 25.0
        if snapshot.reproducibility.get("test_in_ci"):
            score += 25.0
        return round(min(100.0, score), 1)

    @staticmethod
    def _architecture_score(snapshot: RepoMetricsSnapshot) -> float | None:
        score = 0.0
        if snapshot.knowledge.get("has_architecture_md"):
            score += 30.0
        modules = snapshot.interface.get("modules", 0)
        score += min(30.0, modules * 1.5)
        score += min(20.0, snapshot.max_depth * 3.0)
        if snapshot.knowledge.get("adr_count", 0) > 0:
            score += 20.0
        return round(min(100.0, score), 1)

    @staticmethod
    def _determine_status(snapshot: RepoMetricsSnapshot) -> str:
        """Lifecycle, not recency.

        A finished, tagged, reproducible repo with no commits this quarter is *stable*,
        not archived. The old mapping treated silence as decay, which is why mature
        work ranked below whatever happened to be touched last week.
        """
        git = snapshot.git
        total = git.get("total_commits", 0)
        if total == 0:
            return "empty"
        if git.get("commits_30d", 0) > 0:
            return "active"
        if git.get("commits_90d", 0) > 0:
            return "maintenance"
        # Released and reproducible => deliberately finished.
        if git.get("tags", 0) > 0 and snapshot.has_ci:
            return "stable"
        return "dormant"

    # ------------------------------------------------------------------
    # Git helpers
    # ------------------------------------------------------------------
    @staticmethod
    def _git_output(repo_path: Path, args: list[str]) -> str:
        try:
            r = subprocess.run(
                ["git", *args], cwd=repo_path,
                capture_output=True, text=True, timeout=15,
            )
            return r.stdout if r.returncode == 0 else ""
        except (subprocess.TimeoutExpired, OSError):
            return ""

    @classmethod
    def _git_int(cls, repo_path: Path, args: list[str]) -> int:
        try:
            return int(cls._git_output(repo_path, args).strip())
        except ValueError:
            return 0

    def get_head_hash(self, repo_path: Path) -> str:
        return self._git_output(repo_path, ["rev-parse", "HEAD"]).strip()

    # ------------------------------------------------------------------
    # Persistence
    # ------------------------------------------------------------------
    def _save_snapshot(self, snapshots: list[RepoMetricsSnapshot]) -> None:
        now = datetime.now(UTC)
        data = {
            "generated_at": now.isoformat(),
            "repo_count": len(snapshots),
            "repos": [snap.to_dict() for snap in snapshots],
        }
        
        # Save timestamped history
        history_dir = self.metrics_dir / "history"
        history_dir.mkdir(exist_ok=True)
        timestamp = now.strftime("%Y%m%d_%H%M%S")
        (history_dir / f"metrics_snapshot_{timestamp}.json").write_text(json.dumps(data, indent=2))
        
        # Save latest
        (self.metrics_dir / "metrics_snapshot.json").write_text(json.dumps(data, indent=2))
        logger.info("Saved metrics snapshot: %d repos", len(snapshots))

    def load_snapshot(self) -> dict[str, Any] | None:
        p = self.metrics_dir / "metrics_snapshot.json"
        if not p.exists():
            return None
        try:
            return json.loads(p.read_text())
        except Exception:
            return None
