{{- if .Values.cerebro.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cerebro.fullname" . }}-secrets
  labels:
    {{- include "cerebro.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
stringData:
  {{- range $k, $v := .Values.cerebro.secrets }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
{{- end }}
